#!/bin/bash
# Quick reference para FAA v2

echo "════════════════════════════════════════"
echo "  FAA v2 — Quick Reference"
echo "════════════════════════════════════════"
echo ""
echo "📍 Status completo:"
echo "   ./scripts/faa.sh status"
echo ""
echo "🔍 Auditoria:"
echo "   ./scripts/faa.sh validate"
echo ""
echo "⚠️  Ver problemas:"
echo "   ./scripts/faa.sh issues"
echo "   ./scripts/faa.sh issues --critical"
echo ""
echo "📋 Ver plano de ação:"
echo "   ./scripts/faa.sh plan"
echo ""
echo "💾 Criar snapshot:"
echo "   ./scripts/faa.sh snapshot"
echo ""
echo "🤖 JSON para agentes:"
echo "   ./scripts/faa.sh state --json"
echo ""
echo "════════════════════════════════════════"
